export const FETCH_FEATUREFLAGS_SUCCESS = 'FETCH_FEATUREFLAGS_SUCCESS';
export const FETCH_FEATUREFLAGS_FAILURE = 'FETCH_FEATUREFLAGS_FAILURE';
export const SET_FEATUREFLAGS_SUCCESS = 'SET_FEATUREFLAGS_SUCCESS';
export const SET_FEATUREFLAGS_FAILURE = 'SET_FEATUREFLAGS_FAILURE';
